# Based on
# https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication
# https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#git-environment-variables
#
# Required Environment variables:
# GIT_AUTHOR_NAME - Name of tag author
# GIT_AUTHOR_EMAIL - Email of tag author
# GIT_COMMITTER_NAME - Name of tag committer
# GIT_COMMITTER_EMAIL - Email of tag committer
# GH_TOKEN - Token for GitHub actions (tagging, publishing releases)
# NPM_TOKEN - Token for npm publishing workflow

version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      # install dependencies
      - run:
          name: install
          command: yarn
      # lint code
      - run:
          name: lint
          command: yarn lint
      # run tests
      - run:
          name: test
          command: yarn test
      # release
      - run:
          name: release
          command: yarn semantic-release
